# Generated by Django 4.1.4 on 2022-12-30 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playstore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(default='', max_length=2083, unique=True)),
                ('summary', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviews', models.CharField(max_length=200)),
                ('ratings', models.CharField(max_length=200)),
                ('histogram', models.CharField(max_length=200)),
            ],
        ),
    ]
